# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/megn540/Desktop/MEGN540

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/megn540/Desktop/MEGN540

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/megn540/Desktop/MEGN540/CMakeFiles /home/megn540/Desktop/MEGN540//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/megn540/Desktop/MEGN540/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MEGN540

# Build rule for target.
MEGN540: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MEGN540
.PHONY : MEGN540

# fast build rule for target.
MEGN540/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540.dir/build.make CMakeFiles/MEGN540.dir/build
.PHONY : MEGN540/fast

#=============================================================================
# Target rules for targets named MEGN540-atmega32u4

# Build rule for target.
MEGN540-atmega32u4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MEGN540-atmega32u4
.PHONY : MEGN540-atmega32u4

# fast build rule for target.
MEGN540-atmega32u4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/build
.PHONY : MEGN540-atmega32u4/fast

#=============================================================================
# Target rules for targets named LUFA_USB

# Build rule for target.
LUFA_USB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LUFA_USB
.PHONY : LUFA_USB

# fast build rule for target.
LUFA_USB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB.dir/build.make CMakeFiles/LUFA_USB.dir/build
.PHONY : LUFA_USB/fast

#=============================================================================
# Target rules for targets named LUFA_USB-atmega32u4

# Build rule for target.
LUFA_USB-atmega32u4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LUFA_USB-atmega32u4
.PHONY : LUFA_USB-atmega32u4

# fast build rule for target.
LUFA_USB-atmega32u4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/build
.PHONY : LUFA_USB-atmega32u4/fast

#=============================================================================
# Target rules for targets named erase_program

# Build rule for target.
erase_program: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 erase_program
.PHONY : erase_program

# fast build rule for target.
erase_program/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/erase_program.dir/build.make CMakeFiles/erase_program.dir/build
.PHONY : erase_program/fast

#=============================================================================
# Target rules for targets named disassemble_Lab0

# Build rule for target.
disassemble_Lab0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disassemble_Lab0
.PHONY : disassemble_Lab0

# fast build rule for target.
disassemble_Lab0/fast:
	$(MAKE) $(MAKESILENT) -f Lab0-Blink/CMakeFiles/disassemble_Lab0.dir/build.make Lab0-Blink/CMakeFiles/disassemble_Lab0.dir/build
.PHONY : disassemble_Lab0/fast

#=============================================================================
# Target rules for targets named upload_Lab0_eeprom

# Build rule for target.
upload_Lab0_eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab0_eeprom
.PHONY : upload_Lab0_eeprom

# fast build rule for target.
upload_Lab0_eeprom/fast:
	$(MAKE) $(MAKESILENT) -f Lab0-Blink/CMakeFiles/upload_Lab0_eeprom.dir/build.make Lab0-Blink/CMakeFiles/upload_Lab0_eeprom.dir/build
.PHONY : upload_Lab0_eeprom/fast

#=============================================================================
# Target rules for targets named upload_Lab0

# Build rule for target.
upload_Lab0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab0
.PHONY : upload_Lab0

# fast build rule for target.
upload_Lab0/fast:
	$(MAKE) $(MAKESILENT) -f Lab0-Blink/CMakeFiles/upload_Lab0.dir/build.make Lab0-Blink/CMakeFiles/upload_Lab0.dir/build
.PHONY : upload_Lab0/fast

#=============================================================================
# Target rules for targets named Lab0

# Build rule for target.
Lab0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab0
.PHONY : Lab0

# fast build rule for target.
Lab0/fast:
	$(MAKE) $(MAKESILENT) -f Lab0-Blink/CMakeFiles/Lab0.dir/build.make Lab0-Blink/CMakeFiles/Lab0.dir/build
.PHONY : Lab0/fast

#=============================================================================
# Target rules for targets named Lab0-atmega32u4.elf

# Build rule for target.
Lab0-atmega32u4.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab0-atmega32u4.elf
.PHONY : Lab0-atmega32u4.elf

# fast build rule for target.
Lab0-atmega32u4.elf/fast:
	$(MAKE) $(MAKESILENT) -f Lab0-Blink/CMakeFiles/Lab0-atmega32u4.elf.dir/build.make Lab0-Blink/CMakeFiles/Lab0-atmega32u4.elf.dir/build
.PHONY : Lab0-atmega32u4.elf/fast

#=============================================================================
# Target rules for targets named disassemble_Lab1

# Build rule for target.
disassemble_Lab1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disassemble_Lab1
.PHONY : disassemble_Lab1

# fast build rule for target.
disassemble_Lab1/fast:
	$(MAKE) $(MAKESILENT) -f Lab1-Serial/CMakeFiles/disassemble_Lab1.dir/build.make Lab1-Serial/CMakeFiles/disassemble_Lab1.dir/build
.PHONY : disassemble_Lab1/fast

#=============================================================================
# Target rules for targets named upload_Lab1_eeprom

# Build rule for target.
upload_Lab1_eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab1_eeprom
.PHONY : upload_Lab1_eeprom

# fast build rule for target.
upload_Lab1_eeprom/fast:
	$(MAKE) $(MAKESILENT) -f Lab1-Serial/CMakeFiles/upload_Lab1_eeprom.dir/build.make Lab1-Serial/CMakeFiles/upload_Lab1_eeprom.dir/build
.PHONY : upload_Lab1_eeprom/fast

#=============================================================================
# Target rules for targets named upload_Lab1

# Build rule for target.
upload_Lab1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab1
.PHONY : upload_Lab1

# fast build rule for target.
upload_Lab1/fast:
	$(MAKE) $(MAKESILENT) -f Lab1-Serial/CMakeFiles/upload_Lab1.dir/build.make Lab1-Serial/CMakeFiles/upload_Lab1.dir/build
.PHONY : upload_Lab1/fast

#=============================================================================
# Target rules for targets named Lab1

# Build rule for target.
Lab1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab1
.PHONY : Lab1

# fast build rule for target.
Lab1/fast:
	$(MAKE) $(MAKESILENT) -f Lab1-Serial/CMakeFiles/Lab1.dir/build.make Lab1-Serial/CMakeFiles/Lab1.dir/build
.PHONY : Lab1/fast

#=============================================================================
# Target rules for targets named Lab1-atmega32u4.elf

# Build rule for target.
Lab1-atmega32u4.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab1-atmega32u4.elf
.PHONY : Lab1-atmega32u4.elf

# fast build rule for target.
Lab1-atmega32u4.elf/fast:
	$(MAKE) $(MAKESILENT) -f Lab1-Serial/CMakeFiles/Lab1-atmega32u4.elf.dir/build.make Lab1-Serial/CMakeFiles/Lab1-atmega32u4.elf.dir/build
.PHONY : Lab1-atmega32u4.elf/fast

#=============================================================================
# Target rules for targets named disassemble_Lab2

# Build rule for target.
disassemble_Lab2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disassemble_Lab2
.PHONY : disassemble_Lab2

# fast build rule for target.
disassemble_Lab2/fast:
	$(MAKE) $(MAKESILENT) -f Lab2-Timing/CMakeFiles/disassemble_Lab2.dir/build.make Lab2-Timing/CMakeFiles/disassemble_Lab2.dir/build
.PHONY : disassemble_Lab2/fast

#=============================================================================
# Target rules for targets named upload_Lab2_eeprom

# Build rule for target.
upload_Lab2_eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab2_eeprom
.PHONY : upload_Lab2_eeprom

# fast build rule for target.
upload_Lab2_eeprom/fast:
	$(MAKE) $(MAKESILENT) -f Lab2-Timing/CMakeFiles/upload_Lab2_eeprom.dir/build.make Lab2-Timing/CMakeFiles/upload_Lab2_eeprom.dir/build
.PHONY : upload_Lab2_eeprom/fast

#=============================================================================
# Target rules for targets named upload_Lab2

# Build rule for target.
upload_Lab2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab2
.PHONY : upload_Lab2

# fast build rule for target.
upload_Lab2/fast:
	$(MAKE) $(MAKESILENT) -f Lab2-Timing/CMakeFiles/upload_Lab2.dir/build.make Lab2-Timing/CMakeFiles/upload_Lab2.dir/build
.PHONY : upload_Lab2/fast

#=============================================================================
# Target rules for targets named Lab2

# Build rule for target.
Lab2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab2
.PHONY : Lab2

# fast build rule for target.
Lab2/fast:
	$(MAKE) $(MAKESILENT) -f Lab2-Timing/CMakeFiles/Lab2.dir/build.make Lab2-Timing/CMakeFiles/Lab2.dir/build
.PHONY : Lab2/fast

#=============================================================================
# Target rules for targets named Lab2-atmega32u4.elf

# Build rule for target.
Lab2-atmega32u4.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab2-atmega32u4.elf
.PHONY : Lab2-atmega32u4.elf

# fast build rule for target.
Lab2-atmega32u4.elf/fast:
	$(MAKE) $(MAKESILENT) -f Lab2-Timing/CMakeFiles/Lab2-atmega32u4.elf.dir/build.make Lab2-Timing/CMakeFiles/Lab2-atmega32u4.elf.dir/build
.PHONY : Lab2-atmega32u4.elf/fast

#=============================================================================
# Target rules for targets named disassemble_Lab3

# Build rule for target.
disassemble_Lab3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disassemble_Lab3
.PHONY : disassemble_Lab3

# fast build rule for target.
disassemble_Lab3/fast:
	$(MAKE) $(MAKESILENT) -f Lab3-Encoder/CMakeFiles/disassemble_Lab3.dir/build.make Lab3-Encoder/CMakeFiles/disassemble_Lab3.dir/build
.PHONY : disassemble_Lab3/fast

#=============================================================================
# Target rules for targets named upload_Lab3

# Build rule for target.
upload_Lab3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab3
.PHONY : upload_Lab3

# fast build rule for target.
upload_Lab3/fast:
	$(MAKE) $(MAKESILENT) -f Lab3-Encoder/CMakeFiles/upload_Lab3.dir/build.make Lab3-Encoder/CMakeFiles/upload_Lab3.dir/build
.PHONY : upload_Lab3/fast

#=============================================================================
# Target rules for targets named upload_Lab3_eeprom

# Build rule for target.
upload_Lab3_eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab3_eeprom
.PHONY : upload_Lab3_eeprom

# fast build rule for target.
upload_Lab3_eeprom/fast:
	$(MAKE) $(MAKESILENT) -f Lab3-Encoder/CMakeFiles/upload_Lab3_eeprom.dir/build.make Lab3-Encoder/CMakeFiles/upload_Lab3_eeprom.dir/build
.PHONY : upload_Lab3_eeprom/fast

#=============================================================================
# Target rules for targets named Lab3

# Build rule for target.
Lab3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab3
.PHONY : Lab3

# fast build rule for target.
Lab3/fast:
	$(MAKE) $(MAKESILENT) -f Lab3-Encoder/CMakeFiles/Lab3.dir/build.make Lab3-Encoder/CMakeFiles/Lab3.dir/build
.PHONY : Lab3/fast

#=============================================================================
# Target rules for targets named Lab3-atmega32u4.elf

# Build rule for target.
Lab3-atmega32u4.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab3-atmega32u4.elf
.PHONY : Lab3-atmega32u4.elf

# fast build rule for target.
Lab3-atmega32u4.elf/fast:
	$(MAKE) $(MAKESILENT) -f Lab3-Encoder/CMakeFiles/Lab3-atmega32u4.elf.dir/build.make Lab3-Encoder/CMakeFiles/Lab3-atmega32u4.elf.dir/build
.PHONY : Lab3-atmega32u4.elf/fast

#=============================================================================
# Target rules for targets named disassemble_Lab4

# Build rule for target.
disassemble_Lab4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disassemble_Lab4
.PHONY : disassemble_Lab4

# fast build rule for target.
disassemble_Lab4/fast:
	$(MAKE) $(MAKESILENT) -f Lab4-MotorPWM/CMakeFiles/disassemble_Lab4.dir/build.make Lab4-MotorPWM/CMakeFiles/disassemble_Lab4.dir/build
.PHONY : disassemble_Lab4/fast

#=============================================================================
# Target rules for targets named upload_Lab4_eeprom

# Build rule for target.
upload_Lab4_eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab4_eeprom
.PHONY : upload_Lab4_eeprom

# fast build rule for target.
upload_Lab4_eeprom/fast:
	$(MAKE) $(MAKESILENT) -f Lab4-MotorPWM/CMakeFiles/upload_Lab4_eeprom.dir/build.make Lab4-MotorPWM/CMakeFiles/upload_Lab4_eeprom.dir/build
.PHONY : upload_Lab4_eeprom/fast

#=============================================================================
# Target rules for targets named upload_Lab4

# Build rule for target.
upload_Lab4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab4
.PHONY : upload_Lab4

# fast build rule for target.
upload_Lab4/fast:
	$(MAKE) $(MAKESILENT) -f Lab4-MotorPWM/CMakeFiles/upload_Lab4.dir/build.make Lab4-MotorPWM/CMakeFiles/upload_Lab4.dir/build
.PHONY : upload_Lab4/fast

#=============================================================================
# Target rules for targets named Lab4

# Build rule for target.
Lab4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab4
.PHONY : Lab4

# fast build rule for target.
Lab4/fast:
	$(MAKE) $(MAKESILENT) -f Lab4-MotorPWM/CMakeFiles/Lab4.dir/build.make Lab4-MotorPWM/CMakeFiles/Lab4.dir/build
.PHONY : Lab4/fast

#=============================================================================
# Target rules for targets named Lab4-atmega32u4.elf

# Build rule for target.
Lab4-atmega32u4.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab4-atmega32u4.elf
.PHONY : Lab4-atmega32u4.elf

# fast build rule for target.
Lab4-atmega32u4.elf/fast:
	$(MAKE) $(MAKESILENT) -f Lab4-MotorPWM/CMakeFiles/Lab4-atmega32u4.elf.dir/build.make Lab4-MotorPWM/CMakeFiles/Lab4-atmega32u4.elf.dir/build
.PHONY : Lab4-atmega32u4.elf/fast

#=============================================================================
# Target rules for targets named upload_Lab5_eeprom

# Build rule for target.
upload_Lab5_eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab5_eeprom
.PHONY : upload_Lab5_eeprom

# fast build rule for target.
upload_Lab5_eeprom/fast:
	$(MAKE) $(MAKESILENT) -f Lab5-Control/CMakeFiles/upload_Lab5_eeprom.dir/build.make Lab5-Control/CMakeFiles/upload_Lab5_eeprom.dir/build
.PHONY : upload_Lab5_eeprom/fast

#=============================================================================
# Target rules for targets named upload_Lab5

# Build rule for target.
upload_Lab5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload_Lab5
.PHONY : upload_Lab5

# fast build rule for target.
upload_Lab5/fast:
	$(MAKE) $(MAKESILENT) -f Lab5-Control/CMakeFiles/upload_Lab5.dir/build.make Lab5-Control/CMakeFiles/upload_Lab5.dir/build
.PHONY : upload_Lab5/fast

#=============================================================================
# Target rules for targets named Lab5

# Build rule for target.
Lab5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab5
.PHONY : Lab5

# fast build rule for target.
Lab5/fast:
	$(MAKE) $(MAKESILENT) -f Lab5-Control/CMakeFiles/Lab5.dir/build.make Lab5-Control/CMakeFiles/Lab5.dir/build
.PHONY : Lab5/fast

#=============================================================================
# Target rules for targets named disassemble_Lab5

# Build rule for target.
disassemble_Lab5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 disassemble_Lab5
.PHONY : disassemble_Lab5

# fast build rule for target.
disassemble_Lab5/fast:
	$(MAKE) $(MAKESILENT) -f Lab5-Control/CMakeFiles/disassemble_Lab5.dir/build.make Lab5-Control/CMakeFiles/disassemble_Lab5.dir/build
.PHONY : disassemble_Lab5/fast

#=============================================================================
# Target rules for targets named Lab5-atmega32u4.elf

# Build rule for target.
Lab5-atmega32u4.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Lab5-atmega32u4.elf
.PHONY : Lab5-atmega32u4.elf

# fast build rule for target.
Lab5-atmega32u4.elf/fast:
	$(MAKE) $(MAKESILENT) -f Lab5-Control/CMakeFiles/Lab5-atmega32u4.elf.dir/build.make Lab5-Control/CMakeFiles/Lab5-atmega32u4.elf.dir/build
.PHONY : Lab5-atmega32u4.elf/fast

c_lib/Battery_Monitor.obj: c_lib/Battery_Monitor.c.obj

.PHONY : c_lib/Battery_Monitor.obj

# target to build an object file
c_lib/Battery_Monitor.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Battery_Monitor.c.obj
.PHONY : c_lib/Battery_Monitor.c.obj

c_lib/Battery_Monitor.i: c_lib/Battery_Monitor.c.i

.PHONY : c_lib/Battery_Monitor.i

# target to preprocess a source file
c_lib/Battery_Monitor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Battery_Monitor.c.i
.PHONY : c_lib/Battery_Monitor.c.i

c_lib/Battery_Monitor.s: c_lib/Battery_Monitor.c.s

.PHONY : c_lib/Battery_Monitor.s

# target to generate assembly for a file
c_lib/Battery_Monitor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Battery_Monitor.c.s
.PHONY : c_lib/Battery_Monitor.c.s

c_lib/Controller.obj: c_lib/Controller.c.obj

.PHONY : c_lib/Controller.obj

# target to build an object file
c_lib/Controller.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Controller.c.obj
.PHONY : c_lib/Controller.c.obj

c_lib/Controller.i: c_lib/Controller.c.i

.PHONY : c_lib/Controller.i

# target to preprocess a source file
c_lib/Controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Controller.c.i
.PHONY : c_lib/Controller.c.i

c_lib/Controller.s: c_lib/Controller.c.s

.PHONY : c_lib/Controller.s

# target to generate assembly for a file
c_lib/Controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Controller.c.s
.PHONY : c_lib/Controller.c.s

c_lib/Encoder.obj: c_lib/Encoder.c.obj

.PHONY : c_lib/Encoder.obj

# target to build an object file
c_lib/Encoder.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Encoder.c.obj
.PHONY : c_lib/Encoder.c.obj

c_lib/Encoder.i: c_lib/Encoder.c.i

.PHONY : c_lib/Encoder.i

# target to preprocess a source file
c_lib/Encoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Encoder.c.i
.PHONY : c_lib/Encoder.c.i

c_lib/Encoder.s: c_lib/Encoder.c.s

.PHONY : c_lib/Encoder.s

# target to generate assembly for a file
c_lib/Encoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Encoder.c.s
.PHONY : c_lib/Encoder.c.s

c_lib/Filter.obj: c_lib/Filter.c.obj

.PHONY : c_lib/Filter.obj

# target to build an object file
c_lib/Filter.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Filter.c.obj
.PHONY : c_lib/Filter.c.obj

c_lib/Filter.i: c_lib/Filter.c.i

.PHONY : c_lib/Filter.i

# target to preprocess a source file
c_lib/Filter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Filter.c.i
.PHONY : c_lib/Filter.c.i

c_lib/Filter.s: c_lib/Filter.c.s

.PHONY : c_lib/Filter.s

# target to generate assembly for a file
c_lib/Filter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Filter.c.s
.PHONY : c_lib/Filter.c.s

c_lib/Lab1_Tasks.obj: c_lib/Lab1_Tasks.c.obj

.PHONY : c_lib/Lab1_Tasks.obj

# target to build an object file
c_lib/Lab1_Tasks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab1_Tasks.c.obj
.PHONY : c_lib/Lab1_Tasks.c.obj

c_lib/Lab1_Tasks.i: c_lib/Lab1_Tasks.c.i

.PHONY : c_lib/Lab1_Tasks.i

# target to preprocess a source file
c_lib/Lab1_Tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab1_Tasks.c.i
.PHONY : c_lib/Lab1_Tasks.c.i

c_lib/Lab1_Tasks.s: c_lib/Lab1_Tasks.c.s

.PHONY : c_lib/Lab1_Tasks.s

# target to generate assembly for a file
c_lib/Lab1_Tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab1_Tasks.c.s
.PHONY : c_lib/Lab1_Tasks.c.s

c_lib/Lab2_Tasks.obj: c_lib/Lab2_Tasks.c.obj

.PHONY : c_lib/Lab2_Tasks.obj

# target to build an object file
c_lib/Lab2_Tasks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab2_Tasks.c.obj
.PHONY : c_lib/Lab2_Tasks.c.obj

c_lib/Lab2_Tasks.i: c_lib/Lab2_Tasks.c.i

.PHONY : c_lib/Lab2_Tasks.i

# target to preprocess a source file
c_lib/Lab2_Tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab2_Tasks.c.i
.PHONY : c_lib/Lab2_Tasks.c.i

c_lib/Lab2_Tasks.s: c_lib/Lab2_Tasks.c.s

.PHONY : c_lib/Lab2_Tasks.s

# target to generate assembly for a file
c_lib/Lab2_Tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab2_Tasks.c.s
.PHONY : c_lib/Lab2_Tasks.c.s

c_lib/Lab3_Tasks.obj: c_lib/Lab3_Tasks.c.obj

.PHONY : c_lib/Lab3_Tasks.obj

# target to build an object file
c_lib/Lab3_Tasks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab3_Tasks.c.obj
.PHONY : c_lib/Lab3_Tasks.c.obj

c_lib/Lab3_Tasks.i: c_lib/Lab3_Tasks.c.i

.PHONY : c_lib/Lab3_Tasks.i

# target to preprocess a source file
c_lib/Lab3_Tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab3_Tasks.c.i
.PHONY : c_lib/Lab3_Tasks.c.i

c_lib/Lab3_Tasks.s: c_lib/Lab3_Tasks.c.s

.PHONY : c_lib/Lab3_Tasks.s

# target to generate assembly for a file
c_lib/Lab3_Tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab3_Tasks.c.s
.PHONY : c_lib/Lab3_Tasks.c.s

c_lib/Lab4_Tasks.obj: c_lib/Lab4_Tasks.c.obj

.PHONY : c_lib/Lab4_Tasks.obj

# target to build an object file
c_lib/Lab4_Tasks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab4_Tasks.c.obj
.PHONY : c_lib/Lab4_Tasks.c.obj

c_lib/Lab4_Tasks.i: c_lib/Lab4_Tasks.c.i

.PHONY : c_lib/Lab4_Tasks.i

# target to preprocess a source file
c_lib/Lab4_Tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab4_Tasks.c.i
.PHONY : c_lib/Lab4_Tasks.c.i

c_lib/Lab4_Tasks.s: c_lib/Lab4_Tasks.c.s

.PHONY : c_lib/Lab4_Tasks.s

# target to generate assembly for a file
c_lib/Lab4_Tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab4_Tasks.c.s
.PHONY : c_lib/Lab4_Tasks.c.s

c_lib/Lab5_Tasks.obj: c_lib/Lab5_Tasks.c.obj

.PHONY : c_lib/Lab5_Tasks.obj

# target to build an object file
c_lib/Lab5_Tasks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab5_Tasks.c.obj
.PHONY : c_lib/Lab5_Tasks.c.obj

c_lib/Lab5_Tasks.i: c_lib/Lab5_Tasks.c.i

.PHONY : c_lib/Lab5_Tasks.i

# target to preprocess a source file
c_lib/Lab5_Tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab5_Tasks.c.i
.PHONY : c_lib/Lab5_Tasks.c.i

c_lib/Lab5_Tasks.s: c_lib/Lab5_Tasks.c.s

.PHONY : c_lib/Lab5_Tasks.s

# target to generate assembly for a file
c_lib/Lab5_Tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Lab5_Tasks.c.s
.PHONY : c_lib/Lab5_Tasks.c.s

c_lib/Message_Handling.obj: c_lib/Message_Handling.c.obj

.PHONY : c_lib/Message_Handling.obj

# target to build an object file
c_lib/Message_Handling.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Message_Handling.c.obj
.PHONY : c_lib/Message_Handling.c.obj

c_lib/Message_Handling.i: c_lib/Message_Handling.c.i

.PHONY : c_lib/Message_Handling.i

# target to preprocess a source file
c_lib/Message_Handling.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Message_Handling.c.i
.PHONY : c_lib/Message_Handling.c.i

c_lib/Message_Handling.s: c_lib/Message_Handling.c.s

.PHONY : c_lib/Message_Handling.s

# target to generate assembly for a file
c_lib/Message_Handling.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Message_Handling.c.s
.PHONY : c_lib/Message_Handling.c.s

c_lib/MotorPWM.obj: c_lib/MotorPWM.c.obj

.PHONY : c_lib/MotorPWM.obj

# target to build an object file
c_lib/MotorPWM.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/MotorPWM.c.obj
.PHONY : c_lib/MotorPWM.c.obj

c_lib/MotorPWM.i: c_lib/MotorPWM.c.i

.PHONY : c_lib/MotorPWM.i

# target to preprocess a source file
c_lib/MotorPWM.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/MotorPWM.c.i
.PHONY : c_lib/MotorPWM.c.i

c_lib/MotorPWM.s: c_lib/MotorPWM.c.s

.PHONY : c_lib/MotorPWM.s

# target to generate assembly for a file
c_lib/MotorPWM.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/MotorPWM.c.s
.PHONY : c_lib/MotorPWM.c.s

c_lib/Ring_Buffer.obj: c_lib/Ring_Buffer.c.obj

.PHONY : c_lib/Ring_Buffer.obj

# target to build an object file
c_lib/Ring_Buffer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Ring_Buffer.c.obj
.PHONY : c_lib/Ring_Buffer.c.obj

c_lib/Ring_Buffer.i: c_lib/Ring_Buffer.c.i

.PHONY : c_lib/Ring_Buffer.i

# target to preprocess a source file
c_lib/Ring_Buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Ring_Buffer.c.i
.PHONY : c_lib/Ring_Buffer.c.i

c_lib/Ring_Buffer.s: c_lib/Ring_Buffer.c.s

.PHONY : c_lib/Ring_Buffer.s

# target to generate assembly for a file
c_lib/Ring_Buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Ring_Buffer.c.s
.PHONY : c_lib/Ring_Buffer.c.s

c_lib/SerialIO.obj: c_lib/SerialIO.c.obj

.PHONY : c_lib/SerialIO.obj

# target to build an object file
c_lib/SerialIO.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/SerialIO.c.obj
.PHONY : c_lib/SerialIO.c.obj

c_lib/SerialIO.i: c_lib/SerialIO.c.i

.PHONY : c_lib/SerialIO.i

# target to preprocess a source file
c_lib/SerialIO.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/SerialIO.c.i
.PHONY : c_lib/SerialIO.c.i

c_lib/SerialIO.s: c_lib/SerialIO.c.s

.PHONY : c_lib/SerialIO.s

# target to generate assembly for a file
c_lib/SerialIO.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/SerialIO.c.s
.PHONY : c_lib/SerialIO.c.s

c_lib/Skid_Steer_Controller.obj: c_lib/Skid_Steer_Controller.c.obj

.PHONY : c_lib/Skid_Steer_Controller.obj

# target to build an object file
c_lib/Skid_Steer_Controller.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Skid_Steer_Controller.c.obj
.PHONY : c_lib/Skid_Steer_Controller.c.obj

c_lib/Skid_Steer_Controller.i: c_lib/Skid_Steer_Controller.c.i

.PHONY : c_lib/Skid_Steer_Controller.i

# target to preprocess a source file
c_lib/Skid_Steer_Controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Skid_Steer_Controller.c.i
.PHONY : c_lib/Skid_Steer_Controller.c.i

c_lib/Skid_Steer_Controller.s: c_lib/Skid_Steer_Controller.c.s

.PHONY : c_lib/Skid_Steer_Controller.s

# target to generate assembly for a file
c_lib/Skid_Steer_Controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Skid_Steer_Controller.c.s
.PHONY : c_lib/Skid_Steer_Controller.c.s

c_lib/Task_Management.obj: c_lib/Task_Management.c.obj

.PHONY : c_lib/Task_Management.obj

# target to build an object file
c_lib/Task_Management.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Task_Management.c.obj
.PHONY : c_lib/Task_Management.c.obj

c_lib/Task_Management.i: c_lib/Task_Management.c.i

.PHONY : c_lib/Task_Management.i

# target to preprocess a source file
c_lib/Task_Management.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Task_Management.c.i
.PHONY : c_lib/Task_Management.c.i

c_lib/Task_Management.s: c_lib/Task_Management.c.s

.PHONY : c_lib/Task_Management.s

# target to generate assembly for a file
c_lib/Task_Management.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Task_Management.c.s
.PHONY : c_lib/Task_Management.c.s

c_lib/Timing.obj: c_lib/Timing.c.obj

.PHONY : c_lib/Timing.obj

# target to build an object file
c_lib/Timing.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Timing.c.obj
.PHONY : c_lib/Timing.c.obj

c_lib/Timing.i: c_lib/Timing.c.i

.PHONY : c_lib/Timing.i

# target to preprocess a source file
c_lib/Timing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Timing.c.i
.PHONY : c_lib/Timing.c.i

c_lib/Timing.s: c_lib/Timing.c.s

.PHONY : c_lib/Timing.s

# target to generate assembly for a file
c_lib/Timing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MEGN540-atmega32u4.dir/build.make CMakeFiles/MEGN540-atmega32u4.dir/c_lib/Timing.c.s
.PHONY : c_lib/Timing.c.s

c_lib/USB_Config/Descriptors.obj: c_lib/USB_Config/Descriptors.c.obj

.PHONY : c_lib/USB_Config/Descriptors.obj

# target to build an object file
c_lib/USB_Config/Descriptors.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.obj
.PHONY : c_lib/USB_Config/Descriptors.c.obj

c_lib/USB_Config/Descriptors.i: c_lib/USB_Config/Descriptors.c.i

.PHONY : c_lib/USB_Config/Descriptors.i

# target to preprocess a source file
c_lib/USB_Config/Descriptors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.i
.PHONY : c_lib/USB_Config/Descriptors.c.i

c_lib/USB_Config/Descriptors.s: c_lib/USB_Config/Descriptors.c.s

.PHONY : c_lib/USB_Config/Descriptors.s

# target to generate assembly for a file
c_lib/USB_Config/Descriptors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.s
.PHONY : c_lib/USB_Config/Descriptors.c.s

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.obj: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.obj: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.obj: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s

lufa/LUFA/Drivers/USB/Core/Events.obj: lufa/LUFA/Drivers/USB/Core/Events.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/Events.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.obj

lufa/LUFA/Drivers/USB/Core/Events.i: lufa/LUFA/Drivers/USB/Core/Events.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/Events.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.i

lufa/LUFA/Drivers/USB/Core/Events.s: lufa/LUFA/Drivers/USB/Core/Events.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/Events.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.s

lufa/LUFA/Drivers/USB/Core/HostStandardReq.obj: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj

lufa/LUFA/Drivers/USB/Core/HostStandardReq.i: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i

lufa/LUFA/Drivers/USB/Core/HostStandardReq.s: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s

lufa/LUFA/Drivers/USB/Core/USBTask.obj: lufa/LUFA/Drivers/USB/Core/USBTask.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/USBTask.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.obj

lufa/LUFA/Drivers/USB/Core/USBTask.i: lufa/LUFA/Drivers/USB/Core/USBTask.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/USBTask.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.i

lufa/LUFA/Drivers/USB/Core/USBTask.s: lufa/LUFA/Drivers/USB/Core/USBTask.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/USBTask.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LUFA_USB"
	@echo "... Lab0"
	@echo "... Lab1"
	@echo "... Lab2"
	@echo "... Lab3"
	@echo "... Lab4"
	@echo "... Lab5"
	@echo "... MEGN540"
	@echo "... disassemble_Lab0"
	@echo "... disassemble_Lab1"
	@echo "... disassemble_Lab2"
	@echo "... disassemble_Lab3"
	@echo "... disassemble_Lab4"
	@echo "... disassemble_Lab5"
	@echo "... erase_program"
	@echo "... upload_Lab0"
	@echo "... upload_Lab0_eeprom"
	@echo "... upload_Lab1"
	@echo "... upload_Lab1_eeprom"
	@echo "... upload_Lab2"
	@echo "... upload_Lab2_eeprom"
	@echo "... upload_Lab3"
	@echo "... upload_Lab3_eeprom"
	@echo "... upload_Lab4"
	@echo "... upload_Lab4_eeprom"
	@echo "... upload_Lab5"
	@echo "... upload_Lab5_eeprom"
	@echo "... LUFA_USB-atmega32u4"
	@echo "... Lab0-atmega32u4.elf"
	@echo "... Lab1-atmega32u4.elf"
	@echo "... Lab2-atmega32u4.elf"
	@echo "... Lab3-atmega32u4.elf"
	@echo "... Lab4-atmega32u4.elf"
	@echo "... Lab5-atmega32u4.elf"
	@echo "... MEGN540-atmega32u4"
	@echo "... c_lib/Battery_Monitor.obj"
	@echo "... c_lib/Battery_Monitor.i"
	@echo "... c_lib/Battery_Monitor.s"
	@echo "... c_lib/Controller.obj"
	@echo "... c_lib/Controller.i"
	@echo "... c_lib/Controller.s"
	@echo "... c_lib/Encoder.obj"
	@echo "... c_lib/Encoder.i"
	@echo "... c_lib/Encoder.s"
	@echo "... c_lib/Filter.obj"
	@echo "... c_lib/Filter.i"
	@echo "... c_lib/Filter.s"
	@echo "... c_lib/Lab1_Tasks.obj"
	@echo "... c_lib/Lab1_Tasks.i"
	@echo "... c_lib/Lab1_Tasks.s"
	@echo "... c_lib/Lab2_Tasks.obj"
	@echo "... c_lib/Lab2_Tasks.i"
	@echo "... c_lib/Lab2_Tasks.s"
	@echo "... c_lib/Lab3_Tasks.obj"
	@echo "... c_lib/Lab3_Tasks.i"
	@echo "... c_lib/Lab3_Tasks.s"
	@echo "... c_lib/Lab4_Tasks.obj"
	@echo "... c_lib/Lab4_Tasks.i"
	@echo "... c_lib/Lab4_Tasks.s"
	@echo "... c_lib/Lab5_Tasks.obj"
	@echo "... c_lib/Lab5_Tasks.i"
	@echo "... c_lib/Lab5_Tasks.s"
	@echo "... c_lib/Message_Handling.obj"
	@echo "... c_lib/Message_Handling.i"
	@echo "... c_lib/Message_Handling.s"
	@echo "... c_lib/MotorPWM.obj"
	@echo "... c_lib/MotorPWM.i"
	@echo "... c_lib/MotorPWM.s"
	@echo "... c_lib/Ring_Buffer.obj"
	@echo "... c_lib/Ring_Buffer.i"
	@echo "... c_lib/Ring_Buffer.s"
	@echo "... c_lib/SerialIO.obj"
	@echo "... c_lib/SerialIO.i"
	@echo "... c_lib/SerialIO.s"
	@echo "... c_lib/Skid_Steer_Controller.obj"
	@echo "... c_lib/Skid_Steer_Controller.i"
	@echo "... c_lib/Skid_Steer_Controller.s"
	@echo "... c_lib/Task_Management.obj"
	@echo "... c_lib/Task_Management.i"
	@echo "... c_lib/Task_Management.s"
	@echo "... c_lib/Timing.obj"
	@echo "... c_lib/Timing.i"
	@echo "... c_lib/Timing.s"
	@echo "... c_lib/USB_Config/Descriptors.obj"
	@echo "... c_lib/USB_Config/Descriptors.i"
	@echo "... c_lib/USB_Config/Descriptors.s"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.obj"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

